INSERT INTO USERS (USER_ID, FIRSTNAME, SURNAME, EMAIL, PASSWORD, ENABLED, REGISTERED_ON) VALUES (1, 'John', 'Doe', 'jdoe@example.com', 'password123', 1, CURRENT_TIMESTAMP);
INSERT INTO USERS (USER_ID, FIRSTNAME, SURNAME, EMAIL, PASSWORD, ENABLED, REGISTERED_ON) VALUES (2, 'Mary', 'Doe', 'mdoe@example.com', 'password123', 1, CURRENT_TIMESTAMP);

INSERT INTO ROLES (ROLE_ID, ROLE) VALUES (1, 'TRAINEE');
INSERT INTO ROLES (ROLE_ID, ROLE) VALUES (2, 'ADMIN');
INSERT INTO ROLES (ROLE_ID, ROLE) VALUES (3, 'MANAGER');

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 3);


INSERT INTO COURSES (COURSE_ID, TITLE, IMAGE_NAME, ENABLED) VALUES (1, 'Course 1', 'image1.png', 1);

INSERT INTO USER_ASSIGNMENT (USER_ASSIGNMENT_ID, ASSIGNED_ON, DEADLINE, LAST_UPDATED, COURSE_ID, USER_ID, STATUS, current_stage_id) VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, 'INCOMPLETE', 0);